###
//Create a user
POST http://localhost:5000/user
Content-Type: application/json

{
    "nama":"Admin",
    "username":"admin",
    "password": "admin",        
    "no_induk":"00113414105",
    "no_telp":"0001123",
    "role": "Dosen"   
}

###

GET     http://localhost:5000/user
Content-Type: application/json


###

GET   http://localhost:5000/absentodayquery?aslab_id=3
Content-Type: application/json

###
//Create a user
POST http://localhost:5000/absen
Content-Type: application/json

{
    "nama":"Jhonatan riski",
    "alamat":"Jl musi",
    "no_telp":"083141",
    "keperluan":"seminar",
    "keterangan":"internasional",    
    "aslab_id":"3"
    
    
}

